spring:
  application:
    name: ms-saga
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        default-requeue-rejected: false   # apos esgotar retries, dead-letter para bantads.dlx
        retry:
          enabled: true
          initial-interval: 2000ms
          max-retries: 3
          multiplier: 2.0
          max-interval: 16000ms

server:
  port: ${SERVER_PORT:40010}

logging:
  level:
    "[br.dac.bantads.ms_saga]": DEBUG
