spring:
  application:
    name: ms-cliente
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cliente}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:teste}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        default-requeue-rejected: false   # apos esgotar retries, dead-letter para bantads.dlx
        retry:
          enabled: true
          initial-interval: 2000ms
          max-retries: 3
          multiplier: 2.0
          max-interval: 16000ms
  mail:
    host: smtp.gmail.com
    port: 587
    username: bantads.dac777@gmail.com
    password: yryoupkptmuppphw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

services:
  conta: ${MS_CONTA_URL:http://localhost:40006}
